name = "ANaiveJuliaTutorial"
uuid = "72f728b0-723e-4d62-880d-0ef2f82424a2"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
